In [122]:
import numpy as np

class PCA:
    def __init__(self, data):
        self.data = data

    def centered_data(self):
        return self.data - np.mean(self.data, axis=0)

    def cov_matrix(self, data):
        return np.cov(data, rowvar=False, ddof=1)

    def eigens(self):
        cov_matrix = self.cov_matrix(self.centered_data())
        eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
        return eigenvalues, eigenvectors

    def order_and_merge(self):
        eigenvalues, eigenvectors = self.eigens()
        sorted_indices = np.argsort(eigenvalues)[::-1]
        sorted_eigenvectors = eigenvectors[:, sorted_indices]
        # Signs of second row are different from the notes.
        # It's about normalization and not important for pca apperantly. 
        return sorted_eigenvectors
        
    def get_principle_components(self, n_comp = -1):
        v = self.order_and_merge()
        d = self.centered_data()
        return d @ v
        

In [123]:
data = np.array([
    [126, 78],
    [128, 80],
    [128, 82],
    [130, 82],
    [130, 84],
    [132, 86]
])

In [127]:
pca = PCA(data)
pcas = pca.get_principle_components()
pcas

array([[ 4.99953747,  0.06800833],
       [ 2.20523715, -0.37003933],
       [ 0.58906316,  0.80808699],
       [-0.58906316, -0.80808699],
       [-2.20523715,  0.37003933],
       [-4.99953747, -0.06800833]])

In [142]:
pca.cov_matrix(data)

array([[4.4, 5.6],
       [5.6, 8. ]])

In [143]:
pca.cov_matrix(pcas)

array([[ 1.20821765e+01, -1.61413893e-16],
       [-1.61413893e-16,  3.17823532e-01]])